### PR TITLE
System data validation

### PR DESCRIPTION
**Pull request by fd**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 635246712f6fdbeaf74cd4a28596a935f07e4f40
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fd/featherhead

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 635246712f6fdbeaf74cd4a28596a935f07e4f40
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: daa7c7f6343bf150b2d5469949c145845aaaabd0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fd/featherhead

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 13d91fa221c7811370da2de5fdbc611a9e8e10a7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fd/featherhead

---
This message was auto-generated by https://gitcop.com

**Comment by fd** [comment]
superseded by #75

**Pull request closed without merging**
